### ISSUE TITLE
Add CRUD helpers

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#128]

**Comment by rehmanis** [comment]
Is this something what you are referring to https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/database.py ?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis automating the endpoints /delete /update and relevent codes
