### ISSUE TITLE
Add is_manufacturer to people module and add relevent info

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#155]
Add a checkbox in people module to check if person manufacturer

Add more fields to fill in his business details

**Comment by kratikasinghal** [comment]
hi! @Abdur-rahmaanJ can I take this issue?

**Comment by sennahLessert** [comment]
i'll do this

**Comment by Abdur-rahmaanJ** [comment]
Some people commented but i cant see them. They deleted maybe

**Comment by sid-7** [comment]
what other fields do you expect?

**Comment by Abdur-rahmaanJ** [comment]
Business name

Business Address

Business Number

Feel free to add more but keep them optional (nullable=false)

**Comment by Abdur-rahmaanJ** [comment]
Business name

Business Address

Business Number

Feel free to add more but keep them optional (nullable=false)

**Comment by Abdur-rahmaanJ** [comment]
Business name

Business Address

Business Number

Feel free to add more but keep them optional (nullable=false)

**Comment by sid-7** [comment]
I can do that

**Comment by Abdur-rahmaanJ** [comment]
Assigned!
