### ISSUE TITLE
Accept only alphanumeric underscore names as startapp command

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#159]
See [https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/cmd.py](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/cmd.py#l66). In create module. Check module name for alphanumeric underscore only.

**Comment by sid-7** [comment]
what do you expect if the module name does not match the specifications?

**Comment by Abdur-rahmaanJ** [comment]
print an error saying name not valid & sys.exit

**Comment by sid-7** [comment]
will do that
