### ISSUE TITLE
Add travil yaml file to build docs upon push

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#163]
See in docs [https://Abdur-RahmaanJ.github.io/shopyo/docs.html](https://Abdur-RahmaanJ.github.io/shopyo/docs.html) the build command

**Comment by sid-7** [comment]
you just need a .travis.yml file?

**Comment by Abdur-rahmaanJ** [comment]
yes since we have travis enabled

**Comment by ImagineZero0** [comment]
Is somebody working on this, If not can I work on it?

**Comment by Abdur-rahmaanJ** [comment]
ok @ImagineZero0 you can have a try!

**Comment by ImagineZero0** [comment]
I have made the required PR for the issue #163. 
Please verify it respectively..
This has really helped me to understand the intricacies of Open Source

**Comment by sid-7** [comment]
Can I work on this?

**Comment by Abdur-rahmaanJ** [comment]
@sid-7 ok
