### ISSUE TITLE
Add clean support for non-sqlite db

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#165]
Clean if mysql-like db wipes out everything in db.

**Comment by sid-7** [comment]
would this support be for any specific non-sqlite database? Can you explain a bit more?

**Comment by Abdur-rahmaanJ** [comment]
MySQL to begin with. Like delete all tables including alembic_version

**Comment by sid-7** [comment]
So I can create a python script to delete all tables in a database including metadata tables. Sounds good?

**Comment by Abdur-rahmaanJ** [comment]
Add the function under the clean command in the manage.py file
