### ISSUE TITLE
Add configuration management section to the docs

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#167]
Add a configuration.rst to sphinx_source. Write how config is handled in Shopyo.

**Comment by ImagineZero0** [comment]
Hey @Abdur-rahmaanJ  Can I work on this.?

**Comment by Abdur-rahmaanJ** [comment]
@ImagineZero0 Yes!

**Comment by ImagineZero0** [comment]
Hey @Abdur-rahmaanJ, Could you inform me what exactly do I have to add in the Configuration.rst...

**Comment by Abdur-rahmaanJ** [comment]
@ImagineZero0 Like the fact that you have different configuration profiles like dev production etc and that you specify the environment in config.json
