### ISSUE TITLE
custom 404 error page

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#169]

**Comment by utkarsh4321** [comment]
hii @Abdur-rahmaanJ what to do into this.

**Comment by Abdur-rahmaanJ** [comment]
@utkarsh4321 ok!

**Comment by memoglr** [comment]
@utkarsh4321 I see the problem on the Info.json for the module change the "panel_redirect":"/contact/dashboard" to "panel_redirect":"/dashboard", could you do this and send the PR, please.

![image](https://user-images.githubusercontent.com/48573164/96287895-2edba100-0fa8-11eb-9e87-db30d2b7bb28.png)

**Comment by utkarsh4321** [comment]
@memoglr sure
