### ISSUE TITLE
Add Sales & reports module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#181]

**Comment by aggdeepika** [comment]
Hi, I want to know about project and issue.

**Comment by Abdur-rahmaanJ** [comment]
Pull your data from the transation model!

**Comment by jctan** [comment]
Hi @Abdur-rahmaanJ is this issue still open? I'd like to dive into it! Send me more details on it, would love to take a look :)

**Comment by Abdur-rahmaanJ** [comment]
@jctan We need to visualise sales. Sales occur on POS transactions and ecommerce. Be creative and create a new module like maybe reports via python manage.py startapp reports. See how other modules add dashboard, view how other modules operate and do it. Any question even the most simplest ping me here or on arj.python at gmail dot com
