### ISSUE TITLE
Not able to Initialise the App

### ISSUE THREAD

**Issue by memoglr** [Abdur-rahmaanJ/shopcube#193]
Something is broken, I'm trying to initialise the app but I'm receiving errors that where not there:
Error: Path doesn't exist: '..\\shopyo\\shopyo\\migrations'.  Please use the 'init' command to create a new scripts folder.
Initialising User: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users

It seems that the migrations path is not been created and also the tables for the DB

**Comment by Abdur-rahmaanJ** [comment]
I merged the ongoing PR, migrating from flask script to click added some path issues, fixed by sys.append in app.py
