### ISSUE TITLE
Delete subcategory (PR#198) deletes all subcategories

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#200]

**Comment by rehmanis** [comment]
The bug is that it takes to the wrong url but it does correctly deletes only one category since it seems that we are using subcategory name instead of category name when we delete and redirect to `/<category_name>/sub/`.

**Comment by Abdur-rahmaanJ** [comment]
Must have been tired when coding this ~
