### ISSUE TITLE
TODO: Add Cart and Delivery Options

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#202]

**Comment by ChristianCelora** [comment]
Hello i am Christian. 
I recently approached the open source world and i want to try contribute to this feature.
Do you have additional information for this feature?

**Comment by Abdur-rahmaanJ** [comment]
@ChristianCelora this issue is assigned as i'm working on it, 10000s excuses. Please pick another issue or better. Download the app, get it to run. You will find many areas to contribute ^^_
