### ISSUE TITLE
TODO: Add blog feature

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#203]

**Comment by symrin** [comment]
Hi, Could you tell more about this feature and where it is to be added?

**Comment by Abdur-rahmaanJ** [comment]
@symrin you need to start a new app called blog

python manage.py startapp blog

then define your info etc, see the page app, do about the same for blog

**Comment by jctan** [comment]
@Abdur-rahmaanJ can I give this a shot if no one has taken up on this? thanks!

**Comment by Abdur-rahmaanJ** [comment]
@jctan ok cool. My mail if you have questions: arj.python at gmail dot com

**Comment by MilitusInnocent** [comment]
@jctan good day. I'm totally new to open source and I've been learning web dev for close to a year. I want to contribute on projects but I don't know where to start.

**Comment by rehmanis** [comment]
@MilitusInnocent No worries. I just also started as well. First setup for your environment i.e fork the project. It will then show on your github profile. You can then clone your forked repo locally (`git clone https://github.com/Abdur-rahmaanJ/shopyo`) and run `cd shopyo`.  You also need to create a virtual python environment. Once you have activated the virtual environment, you can then do `python -m pip install -r dev_requirements.txt` to install required packages. Now do `cd shopyo` again and run `python manage.py initialise`. To run the app do `python manage.py runserver` and then go to http://localhost:5000/login/.

Once everything is working, setup an upstream as follows:
```
git remote add upstream https://github.com/Abdur-rahmaanJ/shopyo.git
git fetch upstream
git pull upstream dev
```

If you are stuck or don't know how to do any of the above step let me know. You also join [discord](https://discord.com/invite/k37Ef6w) and ask questions there. If you do not know how to do fork and clone, I followed this readme tutorial which helped me https://github.com/ollelauribostrom/rebus#fork-this-repo. Finally once the app is working you can ping me a message and I will help you with your first contribution by assigning an issue that is first time friendly.

We also have [docs](https://www.appinv.science/shopyo/index.html) but some commands might be old and not work.

my email: shamsuddin.rehmani@gmail.com

**Comment by MilitusInnocent** [comment]
Hi, I really appreciate your response, it means a lot to me.

Unfortunately, I'm a Javascript developer. Is it the same procedure? And do
you have a Javascript, HTML, or CSS open-source you're working on? I'd
gladly contribute.

**Comment by rehmanis** [comment]
The project is more python heavy but it is a web app and we do use lot of HTML, CSS and JavaScript. Is your interest more on the frontend development? What is the procedure you use as a JavaScript developer?

The backend is python focused while frontend is HTML, JavaScript, CSS.

**Comment by MilitusInnocent** [comment]
Yes, I'm a frontend developer aspiring to be fullstack soon. I would really
love to contribute. I'd take up the process immediately. So how do I go
about the html, CSS and Javascript projects?

**Comment by rehmanis** [comment]
How about we discuss more on [discord](https://discord.com/invite/k37Ef6w) since thread focuses on the Add to Blog feature issue? Or if you are not comfortable, we can create a new discussion on github.

**Comment by MilitusInnocent** [comment]
Discord: mockingbird#6899. You can send me a link, too. Thank you.

**Comment by rehmanis** [comment]
Here is the link https://discord.com/invite/k37Ef6w

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ Hi. I want to contribute. I searched for a python command to start our app but can't get it through lots of info. What should I do to start our  app named blog?

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara Join the discord for more support! See the docs here: https://www.appinv.science/shopyo/modules.html

I suggest you see the page module, copy and modify relevent codes, run the migrate command etc 

Join [the discord](https://discord.gg/k37Ef6w) for instant support

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ I am clearly a beginner developer. I run **python manage.py startapp modulename
** then I did not know what to do. So what is next ?^^

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara This might be a tough issue for you, i suggest you take issue #329

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ Done.
