### ISSUE TITLE
TODO: Add currency to product

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#204]

**Comment by tanuj1709** [comment]
Hey! Can you please tell me where to add currency?  I will help you with this!!

**Comment by Abdur-rahmaanJ** [comment]
@tanuj1709 add currency to the product model

https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/product/models.py

in ui in product module add dropdown for all currency in the world
