### ISSUE TITLE
dev_requirements.txt missing packages.

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#209]
After following the https://www.appinv.science/shopyo/setup.html#install-from-github,  ```python manage.py initialise``` gives complie time error.  Seems like ```dev_requirements.txt``` is missing ```email_validator``` and ```pillow```

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis you up for fixing the instructions?

**Comment by Abdur-rahmaanJ** [comment]
And .txt file?

**Comment by rehmanis** [comment]
Yes just sending the pull request

**Comment by rehmanis** [comment]
Apart from the .txt file, what instructions do need me to fix?

**Comment by Abdur-rahmaanJ** [comment]
Tjats all i guess!

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis can you add the discord link in readme? thanks!

**Comment by rehmanis** [comment]
Sure. Another pull request? Do you want me to add another issue for this?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis just PR, no need for issue!

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis Just PR, no need to open issue!

**Comment by rehmanis** [comment]
sounds good
