### ISSUE TITLE
Bug: clicking contact page on Contact dashboard results in crash

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#212]
Reproduce crash: click the `Contact page` under `Contact dashboard`  (`http://localhost:5000/contact/` for local testing and 'http://shopyo.pythonanywhere.com/contact/' for live).

The error seems to be related to `get_currency_symbol()` not being recognized in `shopyo\themes\boogle\sections\nav.html`

**Comment by Abdur-rahmaanJ** [comment]
Let me fix this

**Comment by Abdur-rahmaanJ** [comment]
Not working on python anywhere as you described. Working for me on local XD. Yes the function is not there that's why!

**Comment by rehmanis** [comment]
So it works for you locally? I can see the function as well which is defined in `shopyo\modules\shop\view.py`. What do you mean function is not there ?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis now reinitialised. It was working because of cache, now no longer. I mean not there in the template

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis fixed on dev. Added global.py protocol whereby a module can make a template var available everywhere. See [https://abdur-rahmaanj.github.io/shopyo/modules.html#global-py](https://abdur-rahmaanj.github.io/shopyo/modules.html#global-py)


Confirm fix and close issue

**Comment by rehmanis** [comment]
Yes working now on `dev` branch.
