### ISSUE TITLE
Bug: incorrectly allowed to add same category and subcategory name if case sensitive

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#222]
Current category blueprint and model allows adding same name if case differs. Example category with name "test" and another category with name "Test" can both be added (route for adding category is http://localhost:5000/category/add)

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ To fix, we have two options:
1- We can not allow lower case category name to be saved inside the database.
2- The second option is to allow any case in the model but in the `category_exists` class function, we convert the name to lower case before the check.

Which is the desired effect? I am assuming the second one.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis

Allow only lowercase in model, convert userinput before searching. convert to uppercase on displaying

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ Okay also want to confirm before PR for the fix. Currently the subcategory name is not set to be unique. Is there a reason why this is the case or just a bug as well? I think it should also be set to unique. 

Edit: Nevermind. It should only be unique for given category i.e it is not globally unique
