### ISSUE TITLE
TODO: make the web app responsive

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#252]
Currently, if you reduce the window size the layout messes up. We can use bootstrap grid layout (https://getbootstrap.com/docs/5.0/layout/grid/) to make the app responsive to small, medium and large screen size. 

Edit: We can also use the `table-responsive` bootstrap class which might be easier where ever we are using `table` class.

To start we can make the dashboard(http://localhost:5000/dashboard/), and admin (http://localhost:5000/admin/) page responsive. 

Note: app runs locally at http://localhost:5000/. Login and then it redirects to the dashboard. You can then click the admin card to reach the admin page

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis you have a screenshot?

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ 
Sure for small screen it looks like this:
![image](https://user-images.githubusercontent.com/5404500/103851911-d254c300-5078-11eb-8e6a-d5589883d720.png)

For medium screen it looks like this:
![image](https://user-images.githubusercontent.com/5404500/103852013-0a5c0600-5079-11eb-8d24-35777edb8f71.png)

**Comment by Abdur-rahmaanJ** [comment]
Oh i guess we just need to add the table-responsive class with table class

**Comment by rehmanis** [comment]
> Oh i guess we just need to add the table-responsive class with table class

Yes I guess if we are using table class than that would work. But not sure about small screen for our case, it might still not look good. We might have more control with column grid. Anyways its a frontend design issue which has many ways of doing it. We can play around and see.

**Comment by Abdur-rahmaanJ** [comment]
.table-responsive when added

![shopyo_admin_responsive](https://user-images.githubusercontent.com/22630684/104084023-e6591a00-525c-11eb-9edf-beb75000ce2c.png)

**Comment by rehmanis** [comment]
Looks good for now. We just need to check this for each module but for this issue we can just do admin.

**Comment by balaajimuthukumar** [comment]
Hai guys, I would like to claim this issue!

**Comment by balaajimuthukumar** [comment]
Hello guys, I couldn't contribute much lately. Somebody has already contributed to it. I don't find any issue related to the issue that has been raised!
