### ISSUE TITLE
TODO: add a timer for flash message to auto hide

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#254]
We can add a timer for all flash messages to auto hide (for example after 5 secs) so that user does not have to manually close the notification every time.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis you'd have to use  a js notify lib for that instead of the default bootstrap one. I suggest finding one, adding the url in theme resources and base resources and modify shopyoapi/html.py

**Comment by rehmanis** [comment]
> @rehmanis you'd have to use a js notify lib for that instead of the default bootstrap one. I suggest finding one, adding the url in theme resources and base resources and modify shopyoapi/html.py

I was just thinking a basic timer like this that we can add in [`shopyo\modules\box__default\base\templates\base\blocks\flashed_messages.html`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/base/templates/base/blocks/flashed_messages.html) not sure if that is the best place to add.

```javascript

setTimeout(function() {
    $('#flashed-messages').fadeOut('fast');
}, 5000); // <-- time in milliseconds (5 secs)

```

So you suggest add this code to [`shopyapi/html.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/html.py)? I see our notification comes from the backend [`notify(message, alert_type="primary")`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/html.py#L7) function in [`shopyoapi/html.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/html.py) and ideally would be best to add the timer functionally there.

**Comment by Abdur-rahmaanJ** [comment]
Oh nice way, just #flashed-messages will target all. You'd want to target by class to target individually. $('.alert').fadeOut ...

**Comment by tom-shanahan** [comment]
I'd be happy to do this. Is it still open?

**Comment by rehmanis** [comment]
> I'd be happy to do this. Is it still open?

Yes absolutely. Let me know if you have any trouble setting up the repo.

You can find instructions to setup at https://www.appinv.science/shopyo/contrib.html#setup-instructions and instructions to make pull request at https://www.appinv.science/shopyo/contrib.html#making-a-pull-request

For more detailed discussion or questions you can join https://discord.com/invite/k37Ef6w

**Comment by balaajimuthukumar** [comment]
I would like to claim this issue!
