### ISSUE TITLE
Docs: update docs instructions for setting up shopyo

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#256]
Current instructions for setting up for first time contributors are not clear.
- we should add instructions to create virtual environment
- Replace `cd shopyo/shopyo` to `cd shopyo` at https://www.appinv.science/shopyo/setup.html#install-from-github since the `dev_requirements.txt` is located at the root (or we move `dev_requirements.txt` to `shopyo/shopyo`
- Add all instructions in one place i.e we should add detail steps for fork, clone, virtual env, app initialize, app run, etc to https://github.com/Abdur-rahmaanJ/shopyo.git. Also add the update fork step here as well and mention that we need to run `git fetch upstream` and `git pull upstream master` before everytime we are making a new branch to work on an issue. 
- Add basic git commands for creating branch, git stash etc that might be useful
- Add that the app runs on http://localhost:5000/ (since the link generated by when you run app command is http://0.0.0.0:5000/ and this does not work)
- Replace username with email `admin@domain.com` here https://www.appinv.science/shopyo/setup.html#default-password
- any other details that might make setup easier

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis You take the issue?

**Comment by rehmanis** [comment]
Sure
