### ISSUE TITLE
Todo: test settings module

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#266]
For this issue, you need to write functional tests for view functions located inside `shopyo/modules/box__default/settings/view.py`

Steps to do:
- make sure you have setup the repo correctly. Setup instructions can be found [here](https://www.appinv.science/shopyo/contrib.html#setup-instructions)
- first review this [article](https://testdriven.io/blog/flask-pytest/). It will help with understanding how `pytests` work. We are following similar structure mentioned in the article. 
- next follow the steps 1 to 3 for [pull request](https://www.appinv.science/shopyo/contrib.html#making-a-pull-request)
- Once you are on a new branch, create folder called `tests` inside `shopyo/modules/box__default/settings` just like one in `shopyo/modules/box__default/admin`.
- inside the `tests` folder create a file `test_settings.py`
- Now follow the `test_admin.py` (located at `shopyo/modules/box__default/admin/tests/test_admin.py`) to first add test class and functions to check all routes in the `shopyo/modules/box__default/settings/view.py` file correctly redirects if not logged in. The code should be almost same as `TestAdminInvalidAuth` in the `test_admin.py` file
- Next write tests for `settings` view functions (`settings_main()`, `settings_edit()`, `settings_update()`). You can start with just a test for one function if you are not comfortable with writing tests for all. Once again test structure should be very similar to `TestAdminAPI` class inside `test_settings.py`
- When you go to `http://localhost:5000/settings/` i.e the `/settings/` route, the  `settings_main()` is called and it renders the `shopyo/modules/box__default/settings/templates/settings/index.html` page. We want to make sure this route is working and so we need a functional test for each route
- There might be cases that would crash these functions. (Example, what happens if you put invalid `settings_name` when calling `/settings/edit/<settings_name>` route i.e. when calling the `settings_edit(settings_name)` function). In this case you might have to change the `view.py` file and add a check for this but only if you feel comfortable doing it.
- to run all test use the command:
```bash
    python -m pytest -v
```

- to run just one test use: 
```bash
    python -m pytest -v -k "<name of the test function>"
```
- to run just all tests within a Test class use: 
```bash
    python -m pytest -v -k "<name of the test class>"
```
- once all tests are passed and you are ready to make a PR, follow steps 6 until the end in the [pull request instructions](https://www.appinv.science/shopyo/contrib.html#making-a-pull-request)

**Comment by rehmanis** [comment]
@valeriocost I added the instructions to make it easier. Take your time but let me know if you are no longer interested in doing this.

**Comment by richpryce** [comment]
Is this issue taken? If not can I be assigned please?

**Comment by rehmanis** [comment]
@prycey77 Yes I can assign you to it but the steps are bit outdated since I changed the test setup recently. Let me update them and in the mean time you can setup the repo by following the guide [here](https://www.appinv.science/shopyo/contrib.html#setup-instructions)

**Comment by richpryce** [comment]
@rehmanis All setup and eager to get started! If I get stuck do I leave a message here?

**Comment by rehmanis** [comment]
@prycey77 I have updated the steps. Also you can join https://discord.com/invite/k37Ef6w if you want to ask questions. But you are welcome to ask questions here as well.

**Comment by rehmanis** [comment]
@prycey77 Also if you have any improvements on existing test setup or approach, please feel free to bring it up.
