### ISSUE TITLE
TODO: add a CRUDMixin base class for db models

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#270]
Create CRUDMixin base class and other helper classes for Database models to minimize repeated code by using something similar to https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/database.py

**Comment by Abdur-rahmaanJ** [comment]
Yes too much copy pasta currently. And if someone wants to use regular models he can. We must go into the spirit of features help, built on top but you can always use the old way

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ Should we place these classes inside `shopyo/shopyoapi/database.py` or is there another suitable place?

**Comment by Abdur-rahmaanJ** [comment]
I think a new models.py in shopyoapi/
