### ISSUE TITLE
assets management: the big picture

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#277]
OPTION 1

each module has it's own assets. the static folder has modules/ which has appropriate module names like

```
static/
    module1/
    box__1/
        modulex/
        moduley/
```

The module's assets are transferred to the static's folders above (command required)

In production the static folder above is moved to the production folder (command required) with path of production folder defined in settings

OPTION 2

All assets are served using a custom function

On production assets folder, after commands it becomes like that:

```
static/
    global_static/

    modules/
        module1/
            assets/
...
```

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ Maybe you can also point out the pros and cons of the 2 options. Might help us to make a decision on which option to chose.
