### ISSUE TITLE
Add Ajax notifications API

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#286]

**Comment by rehmanis** [comment]
Is this for replacing backend flask notification with frontend? Our app is mostly server-side but would be good to add client-side ajax calls depending on the case for example not having to reload the url to update data etc.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis no new features. Just a mechanism to add notification as described here: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxi-user-notifications
