### ISSUE TITLE
Bug: app crashes at admin route if not logged in

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#289]
#### Steps to reproduce the issue

1.  Initialize the app if not done so (`python manage.py initialise`)
2. run the app (`python manage.py runserver`) 
3. go to http://localhost:5000/admin/ without logging in

#### What's the expected result?

- should be able to render the admin page

#### What's the actual result?

- the admin route crashes at  `line 26: if current_user.is_admin is True:` in `shopyo/modules/box__default/admin/admin.py`

#### Additional details / screenshot

- Problem introduced by setting `LOGIN_DISABLED = True` in  class `DevelopmentConfig` of `shopyo/config.py` . I am guessing we need to add a check for `current_user.is_anonymous` in same line 26 as described above.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis i forgot to comment it back ^^, anyways that's a bug nevertheless

**Comment by rehmanis** [comment]
No worries. Its an easy fix with changing line 26 to `if current_user.is_anonymous or current_user.is_admin`
