### ISSUE TITLE
Replace type of string concaternation in cmd.py.

### ISSUE THREAD

**Issue by damiaanh** [Abdur-rahmaanJ/shopcube#292]
The current way of string concat (using +) is not very nice and should be replaced with .format.

**Comment by rehmanis** [comment]
@damiaanh would you be interested in fixing this ?

**Comment by damiaanh** [comment]
sure!

**Comment by rehmanis** [comment]
@damiaanh go with f-string instead of .format where possible.

**Comment by damiaanh** [comment]
yes, will do.
