### ISSUE TITLE
Add relevant classes to admin panel so that theme devs can target the elements better

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#296]
Add the docs also. File to modify: https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/dashboard/templates/dashboard/index.html

possible:

from 
```html
 <div class="card card-menu">
            <div class="card-body text-center">
```
to
```html
 <div class="yo-panel-card card card-menu">
            <div class="yo-panel-card-body card-body text-center">
```

**Comment by Yahyakiani** [comment]
@Abdur-rahmaanJ I'll take this issue if it is available. A question.Do I have to use these classes or a suggested classes such as 
from
` <div class="card card-menu">
            <div class="card-body text-center">`
to
` <div class="admin-dashboard-card card card-menu">
            <div class="admin-dashboard-card card-body text-center">`
would work ?

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ mind explaining how to go about this one? @Yahyakiani you can also join [discord](https://discord.com/invite/k37Ef6w) for more help.

**Comment by Yahyakiani** [comment]
Will do. Thanks
