### ISSUE TITLE
Add author info to Appointment module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#297]
Add author info to [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__bizhelp/appointment/info.json): At least name, if no name, include Github name and website, include his profile url

You have to go back in time to see who is the main contributor to the module!

Add json:

```json
"author": {
        "name":"",
        "website":"",
        "mail":""
    }
```

**Comment by KanchanPrasad** [comment]
I would like to work on it.

**Comment by Abdur-rahmaanJ** [comment]
@KanchanPrasad Assigned! Join [the discord](https://discord.gg/k37Ef6w) if you need help!

**Comment by balaajimuthukumar** [comment]
Hai I have recently Added commits to the file what should I do next? Can I claim the issue?

**Comment by rehmanis** [comment]
@KanchanPrasad please let us know if you are still working on this issue. If not @balaajimuthukumar would like to complete it.

**Comment by KanchanPrasad** [comment]
Sorry sir i have some issue please assign this project to @balaajimuthukumar .

**Comment by rehmanis** [comment]
@KanchanPrasad no worries. There are more issue that you can work later at your convenience.
