### ISSUE TITLE
Change send_from_directory to using static function everywhere

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#298]

**Comment by rehmanis** [comment]
Great. I was thinking about this. This means client side rendering instead of sever side?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis yes as for apache serving etc better. The static one will work same as send from directory now but on apache you configure /static route to serve files from /path/to/static/


see: https://modwsgi.readthedocs.io/en/develop/user-guides/configuration-guidelines.html#hosting-of-static-files

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis regrouping #277 and https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/ we should get what we need to beautifully manage assets. Collectstatic is used to transfer app assets into /static

**Comment by Abdur-rahmaanJ** [comment]
I think better this:
@rehmanis 

created if in our module there is a folder called static
```
static/

    modules/
        module1/
            file.png etc
        modulex/
            file.png
        box__ecommerce/
            moduley/
                file.png
```

url_for('static', filename='modules/box__ecommerce/product/file.png')

in product

```
product/
     static/
     view.py
     ....
```

**Comment by Abdur-rahmaanJ** [comment]
See https://docs.djangoproject.com/en/3.1/intro/tutorial06/

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ this looks a like a breaking change. Will all route now return just JSON or status code and we will only be sending one html file index.html?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis no that is just for managing pictures/files etc (that's what static refers to)
