### ISSUE TITLE
Update the settings_edit route to get by id

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#300]
- Change the `settings_edit` function and its corresponding route to get the setting by id. Instead of rendering edit page, return a json for setting name and value or 400 code. (might want to rename the function as well)
- Change the `shopyo/modules/box__default/settings/templates/settings/index.html` to allow editing the value on the same page rather than redirecting to another route for each `setting_name`

**Comment by Yahyakiani** [comment]
@rehmanis i would like to take this issue if it is not taken.Thanks

**Comment by rehmanis** [comment]
@Yahyakiani I was just discussing with @Abdur-rahmaanJ and he said we might just get rid of settings module which would remove this issue. But if you still like to work on it for practice then I can assign it to you.

**Comment by Yahyakiani** [comment]
If thats the case i ll try to find something that will be useful for this project.
