### ISSUE TITLE
Remove uploads from app.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#301]
Find a way to include codes in module. Maybe add upload.py with function for box and module

**Comment by Yahyakiani** [comment]
i ll take this issue if it is available . Thanks

**Comment by rehmanis** [comment]
@Yahyakiani this is half done so you can complete it see [`shopyo\modules\box__ecommerce\category\upload.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__ecommerce/category/upload.py) for example. The file to work on is [`shopyo/shopyoapi/uploads.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/uploads.py)(basically getting rid of this file and doing something similar to the example above. See also [`shopyo\shopyoapi\cmd.py`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/cmd.py)(mainly the `initialise()` function there) for how we grab the `upload()` function in `upload.py `files from all modules
