### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by mohamedmehdigara** [Abdur-rahmaanJ/shopcube#310]
After running **python manage.py runserver**  the app crashes with the following
![Capture3](https://user-images.githubusercontent.com/47916299/105575519-8db17300-5d6c-11eb-85a4-fdd775afab95.PNG)
![Capture2](https://user-images.githubusercontent.com/47916299/105575522-8e4a0980-5d6c-11eb-8acb-37a536e92357.PNG)
![Capture1](https://user-images.githubusercontent.com/47916299/105575523-8ee2a000-5d6c-11eb-979a-5a2d082e1213.PNG)
![Capture](https://user-images.githubusercontent.com/47916299/105575524-8ee2a000-5d6c-11eb-9d4a-f595cbae294b.PNG)

**Comment by rehmanis** [comment]
Just confirming did you follow the setup instructions https://www.appinv.science/shopyo/contrib.html?

**Comment by mohamedmehdigara** [comment]
@rehmanis Yes.

**Comment by rehmanis** [comment]
And you ran `python manage.py initialise` before the runserver command?

**Comment by mohamedmehdigara** [comment]
@rehmanis Yes.

**Comment by rehmanis** [comment]
It does seem to have not created the tables when you ran `python manage.py initialise`. Can you share the output of what you got when you ran `python manage.py initialise` ?

**Comment by Abdur-rahmaanJ** [comment]
@mohamedmehdigara you used a virtual environment?

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ No. I didn't use a virtual environment.

**Comment by Abdur-rahmaanJ** [comment]
You must use one!

**Comment by Abdur-rahmaanJ** [comment]
Also @mohamedmehdigara  , feel free to join our [discord server](https://discord.gg/k37Ef6w) for extended support ^^, like conversations go faster than github comments!

**Comment by mohamedmehdigara** [comment]
@Abdur-rahmaanJ Thanks brother. The app is running ^^.
