### ISSUE TITLE
Bug: unable to delete category name with hyphen(-)

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#312]
#### Issue description
Unable to delete a category whose name contains a hyphen (-)

#### Steps to reproduce the issue

1. Run the app ( `python manage.py runserver`) assuming you have initialized it.
2. Go to http://localhost:5000/category/add and add category named "cat-1"
3. Go to http://localhost:5000/category/dashboard and delete category name "cat-1"
4. click ok on the pop up alert to delete.

#### What's the expected result?

- category named "cat-1" should be deleted with flash message "Category "cat-1" successfully deleted"

#### What's the actual result?

- unable to delete and getting flash message "Category "cat" does not exist."

#### Additional details / screenshot

- problem lies in file [`/shopyo/modules/box__ecommerce/category/templates/category/dashboard.html`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__ecommerce/category/templates/category/dashboard.html) at [```javaScript
var name = id.split('-')[1];```](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__ecommerce/category/templates/category/dashboard.html#L24)

**Comment by carolz19** [comment]
hi! I'm new to contributing to open source, would this be an okay issue for me to take a shot at?

**Comment by rehmanis** [comment]
@carolz19 sure. It seems like easy fix. To setup the repo and how to make a PR, you can check the documentation here https://www.appinv.science/shopyo/contrib.html

Also you can join our https://discord.com/invite/k37Ef6w if you want want more help or have other questions.

**Comment by carolz19** [comment]
@rehmanis I believe I have a fix for the issue, but I'm a bit confused on how to add tests.

In [shopyo/modules/box__ecommerce/category/tests/test_category.py at line 169](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__ecommerce/category/tests/test_category.py#L169), there's a test that adds a category "test-delete-category" which includes hyphens already. 

Before my fix, adding a category called "test-delete-category" reproduces the original issue, so I guess I'm just wondering why `test_category_delete_get_valid` passes.

**Comment by rehmanis** [comment]
@carolz19 perfect. The reason that test passes is because I call the route directly http://localhost:5000/category/cat-1/delete which deletes correctly as expected. Only functional tests are written so far. However, the bug is a frontend issue(the JavaScript function) and test are not written for the frontend. Hope that make sense.

Also no need to add a test since we do not have any tests for frontend and I need to setup that up. Will update the docs about the PR step for adding tests thanks for pointing it out.

**Comment by carolz19** [comment]
Yep, that makes thanks!
