### ISSUE TITLE
Add author info to contact module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#316]
Add author info to [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__bizhelp/contact/info.json): At least name, if no name, include Github name and website, include his profile url

You have to go back in time to see who is the main contributor to the module!

Add json:

"author": {
        "name":"",
        "website":"",
        "mail":""
    }

**Comment by AshuKV** [comment]
Please assign me this issue. I would like to work on this one too.

**Comment by Abdur-rahmaanJ** [comment]
@AshuKV all ok?

**Comment by akshay4n** [comment]
@Abdur-rahmaanJ Is this issue still open? I would like to work on it

**Comment by Abdur-rahmaanJ** [comment]
@akshay4n Assigned

**Comment by Shubham-Vishwakarma** [comment]
@Abdur-rahmaanJ 
Please close this issue if completed
