### ISSUE TITLE
Add author info to page module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#317]
Add author info to [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__bizhelp/page/info.json): At least name, if no name, include Github name and website, include his profile url

You have to go back in time to see who is the main contributor to the module!

Add json:

"author": {
        "name":"",
        "website":"",
        "mail":""
    }

**Comment by AshuKV** [comment]
Please assign me this issue. I would like to work on this one.

**Comment by Monikajoshi2001** [comment]
I want to work on this issue.

**Comment by Abdur-rahmaanJ** [comment]
@Monikajoshi2001 ok!

**Comment by Abdur-rahmaanJ** [comment]
@Monikajoshi2001 all ok?

**Comment by NicoPlyley** [comment]
I went to take on this issue but I realized you document does not fit the JSON schema. Consider opening an issue to change it.
@Abdur-rahmaanJ the "type" keyword is reserved as well as author and need to match a certain schema, [here](https://json-schema.org/understanding-json-schema/basics.html#the-type-keyword) is a link describing more for the type keyword.

If you would like I will make the changes for now and we can update it in the future.

**Comment by rehmanis** [comment]
@NicoPlyley Thank you for the comment. I think you are confusing a normal JSON file with [JSON schema](https://json-schema.org/understanding-json-schema/about.html). JSON schema is used to validate JSON and is also written in JSON. On the other hand json text is just key-value pairs. You can learn more about json at https://www.w3schools.com/js/js_json_intro.asp. We do not have any JSON schema for `info.json` so the json is valid semantically. You can, for example, check the semantic validity of json file at https://jsonlint.com/ by copy pasting below json:
```json
{
	"display_string": "Manage Shop",
	"module_name": "shopman",
	"type": "show",
	"fa-icon": "fa fa-store",
	"url_prefix": "/shopman",
	"dashboard": "/dashboard",
	"author": {
		"name": "",
		"website": "",
		"mail": ""
	}
}
```

**Comment by NicoPlyley** [comment]
@rehmanis For some reason in my editor this is marked as a JSON Schema v7 file. I can update it I don't know if it is stored in the mimetype or not, but all the other files do show up as regular JSON files. Sorry for the confusion.

**Comment by rehmanis** [comment]
@NicoPlyley no worres. To honest, I have not used JSON Schema so might not know much about it when writing one. It looks like an editor problem. Which editor software are you using? Maybe you can try creating and saving a new file `info.json` (delete the old one and copy paste the content) inside `/shopyo/modules/box__bizhelp/page/`

**Comment by NicoPlyley** [comment]
@rehmanis that's exactly what I did. I am using PyCharm
