### ISSUE TITLE
Add author info to people module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#318]
Add author info to [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__bizhelp/people/info.json): At least name, if no name, include Github name and website, include his profile url

You have to go back in time to see who is the main contributor to the module!

Add json:

"author": {
"name":"",
"website":"",
"mail":""
}

**Comment by Yahyakiani** [comment]
i ll take for my first time contribution.
