### ISSUE TITLE
Add author info to admin module

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#319]
Add author info to [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/admin/info.json): At least name, if no name, include Github name and website, include his profile url

You have to go back in time to see who is the main contributor to the module!

Add json:

"author": {
        "name":"",
        "website":"",
        "mail":""
    }

**Comment by simrangupta234** [comment]
My first open source contri

**Comment by rehmanis** [comment]
@Simran-Gupta234 If you like to work on this, I can assign it to you.

**Comment by KashyapPavra** [comment]
@rehmanis I did not see any pull request for this and other 2 similar issues. Is it fixed or I can contribute?

**Comment by rehmanis** [comment]
@KashyapPavra I have assigned this one to you since no one has claimed it yet. If you want to work on more challenging issue or need any help you can join our [discord group](https://discord.com/invite/k37Ef6w) as well

**Comment by KashyapPavra** [comment]
@rehmanis Thanks. I'll check out the discord group as well.
