### ISSUE TITLE
Add TODO list

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#32]
A todo section. You can add, modify and delete items. You can also cross out items.

**Comment by I-am-Dishon** [comment]
i could contribute to this, i not aware where to start

**Comment by blips5** [comment]
@I-am-Dishon  Hi what are you stuck on. I will try to help if if i can 😃 .

**Comment by I-am-Dishon** [comment]
which items are added? and where are they being added

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon you know flask?

**Comment by I-am-Dishon** [comment]
yes know flask though am a beginner, i need to work on projects to cement my knowledge on what i learn

**Comment by blips5** [comment]
first thing is you need to make a model in models.py file this creates the model for Todo.

next create a view for your model in views 
then make templates for each section of todo i.e. 
* todo_index.html
* todo_edit.html
*todo_add.html

check out model.py and some files in the views and template folder. there some help in the readme on how to make templates.

**Comment by I-am-Dishon** [comment]
ok thank you

**Comment by I-am-Dishon** [comment]
you can assign it to me

**Comment by blips5** [comment]
done 😄 .

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon we just updated, see project structure

**Comment by I-am-Dishon** [comment]
noted, for todo on its model, i am having id and body as columns in the todo table. is that ok or there are additional  fields that need to be added

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon feel free to browse popular todo apps and see best features!

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon add an optional date and time field if you can ^^_

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon Any update?

**Comment by I-am-Dishon** [comment]
@Abdur-rahmaanJ  Apologies for not working on the MR as promised. if possible I can still work on it

**Comment by Abdur-rahmaanJ** [comment]
@I-am-Dishon ok!
