### ISSUE TITLE
Remove settings codes from shopyoapi

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#343]
move get_setting from shopyoapi/enhance.py to settings/helpers.py

**Comment by Yahyakiani** [comment]
@Abdur-rahmaanJ i ll take this issue if its available.Do I simply have to move code between files ?

**Comment by Abdur-rahmaanJ** [comment]
@Yahyakiani also change all imports using get_setting and set_setting
