### ISSUE TITLE
Please use Shopyo in a virtual enviorment

### ISSUE THREAD

**Issue by InfoX1337** [Abdur-rahmaanJ/shopcube#349]
I have just installed shopyo, and when i try to create a project it spits out an error:
Please use Shopyo in a virtual enviorment
if i use it in virtualenv, it still gives an error.

**Comment by rehmanis** [comment]
Just making sure did you follow the setup steps in the docs https://www.appinv.science/shopyo/contrib.html#setup-instructions ?

Also if you can follow this bug report template (https://gist.github.com/carlo/3402842) it will help me reproduce it on my end

**Comment by InfoX1337** [comment]
Actualy, it worked when i reinstalled the system.
