### ISSUE TITLE
Rename startsubapp to startapp box__name/app

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#352]

**Comment by Yahyakiani** [comment]
i ll take this issue.Simply rename folder and change imports right ?

**Comment by Abdur-rahmaanJ** [comment]
@Yahyakiani No, you need to modify command

python manage.py startsubapp apple in box__fruit 

to 

python manage.py startapp box__fruit/apple


now the startapp command is already implemented but, it does not allow app creation in boxes
