### ISSUE TITLE
docs: shared hosting deployment: change  FLASK_APP = app.py to FLASK_APP=app.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#354]
In [this file](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/sphinx_source/shared_hosting.rst) change

`FLASK_APP = app.py` to `FLASK_APP=app.py`

**Comment by richpryce** [comment]
Hi. Can I work on this one please.

**Comment by Yahyakiani** [comment]
Reach out if you require any help.
