### ISSUE TITLE
clean as per db type

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#365]
@rehmanis we can clean db as per type. If using mysql, erase tables. If sqlite delete file. We must think of nice db configs to handle both

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ yeah that good but I am not sure how this can be done. Might have to look into it more.

**Comment by Abdur-rahmaanJ** [comment]
Detect db type by sqlalchemy uri

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ Why not use `SQLALCHEMY_BINDS` to define multiple databases and then clean them as needed?
