### ISSUE TITLE
ideas bin

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#38]
- what if appointmements clash?
- percentage profit ?

**Comment by blips5** [comment]
As there is now multiple forms should we consider intergrating

* flask-wtf

**Comment by blips5** [comment]
Would it be better to remove look up pages for products and appointments and have the search bar on their main pages.

**Comment by flide** [comment]
I did not really understand how is the user suppose to input the inventory? 
Is the user suppose to **type in** the "barcode" manually when adding an Item to the inventory? Or am I missing something?

**Comment by memoglr** [comment]
Yes, you can added manually.

**Comment by flide** [comment]
won't it be great to have a complementary mobile app that can scan barcodes on the items and communicate with the API to get the item added?

**Comment by memoglr** [comment]
> won't it be great to have a complementary mobile app that can scan barcodes on the items and communicate with the API to get the item added?

super cool!!!

**Comment by memoglr** [comment]
> I did not really understand how is the user suppose to input the inventory?
> Is the user suppose to **type in** the "barcode" manually when adding an Item to the inventory? Or am I missing something?

Yes, you can added manually.

**Comment by Abdur-rahmaanJ** [comment]
@flide we can add the feature then when you open the page on mobile, you can scan it! Could you open a new 'Camera to scan barcode issue' ? Thank you 🎉
