### ISSUE TITLE
remove requests from requirements.txt and dev_requirements.txt

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#383]

**Comment by Shivam-Shrivastav** [comment]
I assume that you are getting an error similar to this:
> Invalid requirement: 'requests==2.9.1 [security]'

In order to solve your issue just change:
```diff
- requests==2.9.1 [security]
```
to:
```diff
+ requests[security] == 2.9.1
```

**Comment by Abdur-rahmaanJ** [comment]
@Shivam-Shrivastav we actually dont use requests ^^
