### ISSUE TITLE
Move users and settings functions from conftest to respective modules

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#385]
We can also discuss about it. Like what if someone just want some API app? or we can require API apps to not change those and ship with those as they'll need an admin panel sooner or later

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ which users and setting functions? Currently the global conftest(the root level) is using User and Setting Models. Ideally you would create a local conftest inside the modules for any fixtures used only in that module but User fixtures are used in all modules hence its kept in root conftest for now.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis yes we'll require users to keep box__default
