### ISSUE TITLE
Update login for better UX

### ISSUE THREAD

**Issue by NicoPlyley** [Abdur-rahmaanJ/shopcube#394]
Currently emails are case sensitive. The email input should be coverted to lowercase and checked against a database result also coverted to lowercase. With that method it would also allow backwards compatibility.

**Comment by rehmanis** [comment]
@NicoPlyley yes we have lots of these types of issue to fix. Would like to take up the challenge? There are multiple ways to do this. One way might be to have a `@validates("email")` in User model just like done here [`/shopyo/modules/box__ecommerce/category/models.py#L33`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__ecommerce/category/models.py#L33) which then store all emails in lowercase in database. And you will have covert to lower in the `form.py` and `view.py` files for the auth modules as necessary. Other option is to convert it in frontend before passing to the wtform (i.e do it in  [`/shopyo/modules/box__default/auth/templates/auth/blocks/login_form.html`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/auth/templates/auth/blocks/login_form.html) and `register_from.html` using jinja and pipe it with `lower`.  There might be more elegant way other then these two.
