### ISSUE TITLE
Remove LGTM alerts and warnings for Python

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#402]
Simple fixes. See what you have to fix [here](https://lgtm.com/projects/g/Abdur-rahmaanJ/shopyo/)

**Comment by Shubham-Vishwakarma** [comment]
@Abdur-rahmaanJ 
Just want to confirm once
All unused code have to be removed
So that the alerts disappear?

**Comment by Abdur-rahmaanJ** [comment]
@Shubham-Vishwakarma yes!

**Comment by Shubham-Vishwakarma** [comment]
Thanks 
I would like to take this up and give it a try

**Comment by Shubham-Vishwakarma** [comment]
I have made a PR
But it's failing due to some reason
@Abdur-rahmaanJ Please guide me

**Comment by Shubham-Vishwakarma** [comment]
Is this completed now???

**Comment by Abdur-rahmaanJ** [comment]
@Shubham-Vishwakarma Yes!
