### ISSUE TITLE
Docs: update setup instructions for contribution

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#418]
since we moved requirements.txt files to inside shopyo/shopyo, move step 10 before step 7 for section https://www.appinv.science/shopyo/contrib.html#setup-instructions and update step 1 of  making a PR (https://www.appinv.science/shopyo/contrib.html#making-a-pull-request) where it mentions something about step 9. If there is a way to link steps that might be ideal rather than manually  updating these each time step number changes.

**Comment by Shubham-Vishwakarma** [comment]
@rehmanis 
This seems to be simple one
Please add label of first-timers-only
It would attract new contributors

**Comment by rehmanis** [comment]
> @rehmanis 
> 
> This seems to be simple one
> 
> Please add label of first-timers-only
> 
> It would attract new contributors

Good point. Added. Feel free to pick up an issue even if it does not have first timers only label

**Comment by hasibhassan** [comment]
Can I work on this?

**Comment by rehmanis** [comment]
@hasibhassan yes absolutely. File to modify is located here https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/sphinx_source/contrib.rst.

Once you modify, to build the html run `sphinx-build -b html sphinx_source ../docs` inside `/shopyo/shoypo`
