### ISSUE TITLE
Enhancement: change pasword hashing from werkzeug.security to Flask-Bcrypt

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#423]
Things to add:
- In `requirments.txt` add `Flask-Bcrypt` if not present
- initialise bycrpt in here https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/init.py. Example,
```python
# init.py
from flask_bcrypt import Bcrypt

bcrypt = Bcrypt()
```
- add the bcrypt to `create_app` here https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/app.py#L92. Example:
```python
# app.py
from shopyoapi.init import bcrypt

def create_app(config_name):
    ...
     bcrypt.init_app(app)
    ...
```
- change any uses of `werkzeug.security` for hashing/verifying passwords. I think there are only 2 places we are using but just double check. In VSCode you can do `ctrl + shift + F` and type `check_password_hash` or/and `werkzeug.security` to do a global search. Two places are at https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/auth/models.py#L99 and https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/auth/models.py#L102. Example:
```python
# auth/model.py
from shopyoapi.init import bcrypt
    ...
    @password.setter
    def password(self, plaintext):
        self._password = bcrypt.generate_password_hash(plaintext)

    def check_password(self, password):
        return bcrypt.generate_password_hash(self._password, password))
    ...
```
Just double check from the docs at https://flask-bcrypt.readthedocs.io/en/latest/ for any doubts/ mistakes in above suggestion. Ping here or [discord](https://discord.com/invite/k37Ef6w) if stuck/ want to discuss.

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ Is there any benefit of using Flask-bycrpt? Should we keep what we are using for now? I can't see any advantage of using it but I can open this again if we still want to switch to bycrpt.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis supposedly more secure, that's why there are rounds. A simple hashing does not provide rainbow table attacks

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ currently discussing with the flask pallets and do not see much difference. However, the current one needs to be updated as it is using plain sha_256 which is not good enough. We need to read a bit more but the easiest solution might be to use bcrypt for now. Let me know. I can reopen it or we wait and look into it more.

**Comment by rehmanis** [comment]
We use built in werkzeug.security for now as discussed but use the default method which is 'pbkdf2:sha256'. Source: https://werkzeug.palletsprojects.com/en/1.0.x/utils/#werkzeug.security.generate_password_hash
