### ISSUE TITLE
Fix: generate_password_hash function default method type

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#424]
Change `self._password = generate_password_hash(plaintext, method="sha256"))` to `self._password = generate_password_hash(password)` here https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/auth/models.py#L99. Add a comment to mention that default hashing method is `pbkdf2:sha256`

**Comment by akshitadixit** [comment]
Hello may I work on this? Also please clarify if the above mentioned changes are all that need to be made?

**Comment by rehmanis** [comment]
@akshitadixit yes this is the only change to be made. Assigned.
