### ISSUE TITLE
Bug: model resource/model.py is using code without imports.

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#425]
Fix the https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/resource/models.py file. The `set_hash` and  `check_hash` are using code from not imported lib. @Abdur-rahmaanJ do we even need these functions in these models?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis a copy paste i guess, we need to rework the module so as to

- add all documents vids and text as a resource object
- add a method to have secure unique filenames
