### ISSUE TITLE
Require shopyo new <foldername> to be aphanumeric underscore. 

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#427]
shopyo new . should not be allowed

**Comment by Shubham-Vishwakarma** [comment]
@Abdur-rahmaanJ 

I can try this
A Regex checking can be used here

1. Only . or _ or combination of both should not be allowed??? (Example: ..___)
2. Can the folder name start with number?? (Example: 2_blog)
3. [a-z][A-Z][0-9][_] should be allowed
4. Is special character allowed? ($#%^&)

**Comment by Abdur-rahmaanJ** [comment]
@Shubham-Vishwakarma 

..__ not allowed

Yes can start with number

3. Yes
4. No

**Comment by Shubham-Vishwakarma** [comment]
This is now fixed
Please close if all good https://github.com/Abdur-rahmaanJ/shopyo/pull/449
