### ISSUE TITLE
Docs: Fix the Setup Instructions

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#431]
Since we moved the `requirement.txt` and `dev_requirement.txt` back one level up the directory, we do need step 7 of https://www.appinv.science/shopyo/contrib.html#setup-instructions. Also update step 1 of https://www.appinv.science/shopyo/contrib.html#making-a-pull-request to now refer to step 9 instead of step 10

File to modify is located here https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/sphinx_source/contrib.rst

Once you modify, to build the html run `sphinx-build -b html sphinx_source ../docs` inside `/shopyo/shoypo`. Then add the files generated to the commit as well.

**Comment by Bnseamster** [comment]
Hello, can I try to take a stab at this issue?
