### ISSUE TITLE
Exclude github_banner.png in MANIFEST.in

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#435]
Add in [MANIFEST.in](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/MANIFEST.in):
```
exclude github_banner.png
```

**Comment by Vaibhav-Singh21** [comment]
can I contribute to it.

**Comment by rehmanis** [comment]
@Vaibhav-Singh21 sure. Assigned
