### ISSUE TITLE
Add .example.env with some private config examples

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#441]
Add to `shopyo/` (root level) the file `.example.env` with the content as bellow:
```
SECRET_KEY = "iMUutJJvkH5vcucaU6xF"
MAIL_USERNAME = "myapp@domain.com"
MAIL_PASSWORD = "pass"
MAIL_DEFAULT_SENDER = "myapp@domain.com"
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://db_username:db_password@db_host/db_name"
```

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ instead of adding commented out code (not good) we can add an example environment with this config like this https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/.test.prod.env at root level

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis Commented out code for configs is quite popular in the PHP world. Yes this sounds fine too. Could you create a new secrets.rst explaining the instance folder as well as .text.prod.env's purpose?

**Comment by rehmanis** [comment]
sure will do. It is just to make code easy to read is all and keep things clean.
