### ISSUE TITLE
docs: create section to explain how to use private config (in instance folder) and .env

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#442]

**Comment by akshitadixit** [comment]
Please provide a description.

**Comment by rehmanis** [comment]
@akshitadixit sorry this one requires to write about the current config setup. Since I wrote the current config structure, I will be working on writing about it as it requires some research and explanations on why I chose the current design approach. However, if you want I, will ping you here so you can review my PR once I make it.
