### ISSUE TITLE
Register should not log in user

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#444]
login_user should only be used when logging in user [line](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/modules/box__default/auth/view.py#L52)

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ not a bug but intentional design decision.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis it foils flask_login's mechnisms

The best way to check everything is through writing robust decorators

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis been seeing the flow, the mishap is that login_required's level of security is busted

anybody can navigate to login_required routes freely

**Comment by Abdur-rahmaanJ** [comment]
Ok closing. Just must add more thourough checks to dashboard

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ hmm I am not an expert about the security aspect so can't comment on that aspect but from user experience was a better choice to login on register and show the unconfirmed page. But it can be changed to register then login then show the unconfirmed page. We are at a point that the app is not secure (there are many basic security flaws like password/email has no regex, no two factor authentication, maybe XSS) so it good that you are thinking from security point of view as well as we will have to address them in near future if the frame gets used to build more web applications

**Comment by Abdur-rahmaanJ** [comment]
It's ok!

2FA is tidbit advanced to provide out of the box but good point to include in todo

This one is more about basic access. Users must be warned not to rely on login_required
