### ISSUE TITLE
Readme icons are failing on MacOS and firefox

### ISSUE THREAD

**Issue by Seluj78** [Abdur-rahmaanJ/shopcube#467]
<img width="1680" alt="Screenshot 2021-03-21 at 18 40 44" src="https://user-images.githubusercontent.com/4641317/111915126-0aaf4f00-8a75-11eb-89e6-76ac280bed7e.png">

Maybe use standard emojis like 🔴 and ✅ ?

**Comment by Abdur-rahmaanJ** [comment]
That's Not Cool,

the emojis are in degrading colors from worse to better let me see
