### ISSUE TITLE
enhancement: move to readthedocs

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#469]
Might be better to move docs to readthedocs instead of github pages at it auto-generates (no need to build sphinx locally and also no need to add the html files to git) and allows for versioning docs. 
see https://github.com/readthedocs/readthedocs.org.

**Comment by Abdur-rahmaanJ** [comment]
done: [here](https://shopyo.readthedocs.io/en/latest/?)

**Comment by rehmanis** [comment]
Oh great so should we use that over github.io currently on the README ? By the way is readthedocs better? I know we will have do not need the html destination folder(currently in docs/) and move the source from sphinx_src to doc/ etc right?

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis yes far better as you get pdf for free + auto build just i dont know how exactky to remove what. will find out

**Comment by rehmanis** [comment]
I think the documentation tell us how to setup. Can be done and we can add .readthedoc.yaml later.

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis it's all ok for now without the .yaml
