### ISSUE TITLE
bug: duplicate code for auto config

### ISSUE THREAD

**Issue by rehmanis** [Abdur-rahmaanJ/shopcube#478]
The commit 1aa7c0e7a2fd9d06e870195dc181fc1d74c34c18 added duplicate code to create `instance` folder and config. Code already present in ``create_app``.

Commit 1aa7c0e7a2fd9d06e870195dc181fc1d74c34c18 also broke the app. It no longer complies.

```python
def create_app(config_name):
    ...
    # create empty instance folder and empty config if not present
    try:
        os.makedirs(app.instance_path)
        with open(os.path.join(app.instance_path, "config.py"), "a"):
            pass
    except OSError:
        pass
```

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis woops can you please revert it if you can? else  tomorrow will do
