### ISSUE TITLE
Set logo to shopyo.png

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#479]
1. copy paste shopyo.png into sphinx_source/shopyo.png
2. change https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/sphinx_source/conf.py#L61 to shopyo.png
3. delete shopyo.ico
4. PR

**Comment by xdshivani** [comment]
I would like to work on it.

**Comment by Abdur-rahmaanJ** [comment]
Assigned!
