### ISSUE TITLE
Add kofi link to title in README

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#514]
Change the title to

```
# shopcube [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/S6S2GDNC7)
```

and delete the link above in the README

**Comment by Caldwell-77** [comment]
Hi, can you please assign this issue to me? I'd very much like to work on it! Thank you.
