### ISSUE TITLE
Add permission levels

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#55]
Currently we have only login, not permission control. A basic classification would be admin and non-admin accounts.

**Comment by rhasoff** [comment]
> A basic classification would be admin and non-admin accounts.

This classification already exists in /admin/ and option in /admin/add.
Could you please clarify? What do you mean by permission control -except for accessing admin panel?

**Comment by Abdur-rahmaanJ** [comment]
@rhasoff permission exists, but permission level is about for example having people accounts etc.
Currently admin can access everything. But if we want to restrict access we might want to create other types of accounts. See [https://flask-user.readthedocs.io/en/latest/](https://flask-user.readthedocs.io/en/latest/) for example

**Comment by lynchmar** [comment]
I would like to work on this! I am a first time contributor. Is there any more information you could give about what exactly you're looking for?

**Comment by Abdur-rahmaanJ** [comment]
@lynchmar actually sometimes back we added the role feature. So that's maybe fine for role. Now we need a way to define precedence:

Like laywer have precedence over teachers

If someone is  a lawyer, he can access whatever thing teacher can access 

Lets say doctor has the same level as lawyer. So, lawyer wont be able to access what doctor can. Feel free to implement it your way!  Hint: use dictionaries to handle precedence

**Comment by lynchmar** [comment]
Great, thank you! I will work on that.
